### ISSUE TITLE
i have everything needed but after running the file with node it has an error

### ISSUE THREAD

**Issue by nameplzwork** [alexlwn123/Chesscup-hack#2]
after i run the file it opens chrome in chesscup.org but it doesnt do anything and in cmd shows this error:
[11784:8416:0628/135017.009:ERROR:device_event_log_impl.cc(222)] [13:50:17.008] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
help please

**Comment by nameplzwork** [comment]
im now getting a different error, 
Applicable driver not found; attempting to install with Selenium Manager (Beta)
The version of chrome cannot be detected. Trying with latest driver version

DevTools listening on ws://127.0.0.1:50457/devtools/browser/031cb5cc-9e4e-4a21-9217-91365116dcc1
[3716:3724:0628/143748.913:ERROR:device_event_log_impl.cc(222)] [14:37:48.913] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
C:\Users\odedg\node_modules\selenium-webdriver\lib\webdriver.js:2775
        throw TypeError('each key must be a number or string; got ' + type)
              ^

TypeError: each key must be a number or string; got undefined
    at C:\Users\odedg\node_modules\selenium-webdriver\lib\webdriver.js:2775:15
    at Array.forEach (<anonymous>)
    at WebElementPromise.sendKeys (C:\Users\*****\node_modules\selenium-webdriver\lib\webdriver.js:2770:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (C:\Users\*****\OneDrive\שולחן העבודה\Chesscup-hack-main\script.js:130:3)
    at async main (C:\Users\*****\OneDrive\שולחן העבודה\Chesscup-hack-main\script.js:224:3)

Node.js v18.16.1

**Comment by alexlwn123** [comment]
I added a sample.env.

1. Rename `sample.env` to `.env`
2. Add your username and password
3. Try again

**Comment by nameplzwork** [comment]
after doing that i ran it and it did open chrome and put the right password but not the right username(you actually need email to log in) and i get this error message in cmd:
Applicable driver not found; attempting to install with Selenium Manager (Beta)
The version of chrome cannot be detected. Trying with latest driver version

DevTools listening on ws://127.0.0.1:59357/devtools/browser/e5264760-a92f-4daf-bc64-38f33d107b80
[4984:26712:0628/215833.675:ERROR:device_event_log_impl.cc(222)] [21:58:33.675] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
C:\Users\*****\node_modules\selenium-webdriver\lib\webdriver.js:929
                new error.TimeoutError(
                ^

TimeoutError: Waiting for element to be located By(xpath, //*[@id="testpng"]/div[1]/div/div[1]/div[2]/div[3])
Wait timed out after 15132ms
    at C:\Users\*****\node_modules\selenium-webdriver\lib\webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: ''
}
